# Generated by Django 4.1.1 on 2022-09-07 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('file', models.FileField(upload_to='uploads/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.thread')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.subcategory')),
            ],
        ),
    ]
