# Generated by Django 4.1.1 on 2022-09-10 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='root_thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_root_thread', to='forum.thread'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reply_to', to='forum.thread'),
        ),
    ]
