# Generated by Django 4.1.1 on 2022-09-13 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_thread_root_thread_alter_thread_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
