# Generated by Django 4.1.1 on 2023-05-24 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0005_alter_thread_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='author_email',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='thread',
            name='author_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='thread',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='thread_files/'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.subcategory'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='subject',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
