# Generated by Django 4.1.1 on 2023-05-24 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_thread_author_email_alter_thread_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reply_to', to='forum.thread'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='root_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_root_thread', to='forum.thread'),
        ),
    ]
